// SpecialtyData.jsx · single source of truth for the 5 practice areas
const SPECIALTIES = [
  {
    id: 'trabalho',
    num: '01',
    title: 'Direito do Trabalho',
    iconName: 'briefcase',
    short: 'Defesa de direitos trabalhistas, negociações coletivas e contencioso estratégico para empregados e empregadores.',
    long: 'Atuação consultiva e contenciosa em relações de trabalho. Assessoramos empregados e empregadores em negociações coletivas, compliance trabalhista, defesa em reclamatórias e estruturação de contratos especiais.',
    bullets: [
      'Reclamatórias trabalhistas (defesa e ajuizamento)',
      'Acordos individuais e coletivos',
      'Compliance trabalhista e auditoria preventiva',
      'Rescisões, verbas e equiparações salariais',
      'Defesa em ações de assédio e dano moral',
    ],
    aside: { eyebrow: 'Tese de destaque', title: 'Reconhecimento de vínculo', body: 'Casos de PJ, terceirização e plataformas digitais. Análise da realidade da prestação acima da forma contratual.' },
  },
  {
    id: 'previdenciario',
    num: '02',
    title: 'Direito Previdenciário',
    iconName: 'shield',
    short: 'Aposentadorias, benefícios e revisões junto ao INSS, com planejamento previdenciário individualizado.',
    long: 'Patrocínio em demandas administrativas e judiciais junto ao INSS, incluindo concessão, revisão e restabelecimento de benefícios. Planejamento previdenciário para profissionais autônomos e contribuintes individuais.',
    bullets: [
      'Aposentadoria por tempo, idade e regras de transição',
      'Auxílio-doença, BPC/LOAS e pensão por morte',
      'Revisão da vida toda e tema 1.102 STF',
      'Concessão administrativa e recurso ao CRPS',
      'Planejamento previdenciário sob medida',
    ],
    aside: { eyebrow: 'Para autônomos', title: 'Plano de contribuição', body: 'Cálculo do recolhimento ideal para maximizar o benefício futuro. Análise carreira a carreira.' },
  },
  {
    id: 'familia',
    num: '03',
    title: 'Famílias e Sucessões',
    iconName: 'users',
    short: 'Divórcio, guarda, alimentos, inventário e planejamento sucessório com discrição e cuidado.',
    long: 'Atuação em direito de família e sucessões com sensibilidade ao momento do cliente. Conduzimos divórcios, ações de guarda e alimentos, inventários judiciais e extrajudiciais e planejamento sucessório de patrimônio.',
    bullets: [
      'Divórcio consensual e litigioso',
      'Guarda, regulamentação de convivência e alimentos',
      'União estável (formalização e dissolução)',
      'Inventário e partilha (judicial e extrajudicial)',
      'Testamento e planejamento sucessório',
    ],
    aside: { eyebrow: 'Discrição', title: 'Atendimento reservado', body: 'Reuniões em sala fechada, sem identificação no agendamento, para casos que exigem absoluta privacidade.' },
  },
  {
    id: 'civil',
    num: '04',
    title: 'Direito Civil',
    iconName: 'file-text',
    short: 'Contratos, responsabilidade civil, direito imobiliário e demandas patrimoniais complexas.',
    long: 'Atuação consultiva e contenciosa em obrigações, contratos, responsabilidade civil e direito imobiliário. Elaboração e revisão de contratos, due diligence imobiliária e defesa em ações indenizatórias.',
    bullets: [
      'Contratos civis e empresariais (elaboração e revisão)',
      'Ações de cobrança e execução',
      'Responsabilidade civil e indenizações',
      'Direito imobiliário (compra, venda e locação)',
      'Usucapião e regularização de imóveis',
    ],
    aside: { eyebrow: 'Pré-litígio', title: 'Mediação e acordos', body: 'Resolução negociada antes do processo. Mais rápida, mais discreta e, em geral, mais econômica.' },
  },
  {
    id: 'consumidor',
    num: '05',
    title: 'Direito do Consumidor',
    iconName: 'scale',
    short: 'Defesa em relações de consumo: bancos, planos de saúde, e-commerce e companhias aéreas.',
    long: 'Defesa do consumidor em conflitos com instituições financeiras, planos de saúde, operadoras de telefonia, companhias aéreas e e-commerce. Atuamos em demandas individuais e em ações coletivas estratégicas.',
    bullets: [
      'Negativações indevidas e revisão de contratos bancários',
      'Negativa de cobertura em planos de saúde',
      'Atrasos, cancelamentos e overbooking (aéreo)',
      'Defeitos em produtos e serviços',
      'Vazamento de dados e LGPD aplicada ao consumo',
    ],
    aside: { eyebrow: 'Volume alto', title: 'Atendimento em escala', body: 'Estrutura para conduzir múltiplas demandas similares (bancos, aéreas, e-commerce) com eficiência processual.' },
  },
];

window.SPECIALTIES = SPECIALTIES;
